"""
Custom Test Runner for better test output formatting.
Provides clear demarcation between test classes and detailed summaries.

Initial Generated by Claude 4 Sonnet on 8/25/25 and then modified.
"""

import unittest


class CustomTestResult(unittest.TextTestResult):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_results = {}
        self.current_class = None
    
    def startTest(self, test):
        # Get the test class name
        test_class = test.__class__.__name__
        
        # If this is a new test class, initialize its results
        if test_class != self.current_class:
            if self.current_class is not None:
                # Print results for the previous class
                self._print_class_results(self.current_class)
            
            # Start new class
            self.current_class = test_class
            if test_class not in self.class_results:
                self.class_results[test_class] = {'passed': 0, 'failed': 0, 'errors': 0}
                print(f"\n{'='*60}")
                print(f"Running {test_class} Tests")
                print(f"{'='*60}")
        
        super().startTest(test)
    
    def addSuccess(self, test):
        super().addSuccess(test)
        test_class = test.__class__.__name__
        self.class_results[test_class]['passed'] += 1
        print(f"✓ {test._testMethodName}: PASSED")
    
    def addError(self, test, err):
        super().addError(test, err)
        test_class = test.__class__.__name__
        self.class_results[test_class]['errors'] += 1
        print(f"✗ {test._testMethodName}: ERROR")
    
    def addFailure(self, test, err):
        super().addFailure(test, err)
        test_class = test.__class__.__name__
        self.class_results[test_class]['failed'] += 1
        print(f"✗ {test._testMethodName}: FAILED")
    
    def _print_class_results(self, class_name):
        results = self.class_results[class_name]
        total = results['passed'] + results['failed'] + results['errors']
        
        print(f"\n{'-'*40}")
        print(f"{class_name} Results:")
        print(f"  Passed: {results['passed']}/{total}")
        print(f"  Failed: {results['failed']}/{total}")
        print(f"  Errors: {results['errors']}/{total}")
        
        if results['failed'] == 0 and results['errors'] == 0:
            print(f"  ✔️  All {class_name} tests PASSED!")
        else:
            print(f"  ⚠️  Some {class_name} tests FAILED")
        print(f"{'-'*40}")
    
    def stopTestRun(self):
        # Print results for the last class
        if self.current_class:
            self._print_class_results(self.current_class)
        
        # Print overall summary
        total_passed = sum(results['passed'] for results in self.class_results.values())
        total_failed = sum(results['failed'] for results in self.class_results.values())
        total_errors = sum(results['errors'] for results in self.class_results.values())
        total_tests = total_passed + total_failed + total_errors
        
        print(f"\n{'='*60}")
        print(f"OVERALL TEST SUMMARY")
        print(f"{'='*60}")
        print(f"Total Tests Run: {total_tests}")
        print(f"Passed: {total_passed}")
        print(f"Failed: {total_failed}")
        print(f"Errors: {total_errors}")
        
        if total_failed == 0 and total_errors == 0:
            print(f"\n✔️  ALL TESTS PASSED! ✔️")
        else:
            print(f"\n⚠️  {total_failed + total_errors} test(s) failed or have errors")
        print(f"{'='*60}")
        
        super().stopTestRun()


class CustomTestRunner(unittest.TextTestRunner):
    """
    Custom test runner that uses our enhanced test result class.
    """
    def __init__(self, *args, **kwargs):
        kwargs['resultclass'] = CustomTestResult
        kwargs['verbosity'] = 0  # We'll handle our own output
        super().__init__(*args, **kwargs)


def run_tests_with_custom_runner(*test_classes):
    """
    Convenience function to run tests with the custom runner.
    
    Args:
        *test_classes: Test classes to run
    
    Returns:
        TestResult: The result of the test run
    """
    runner = CustomTestRunner()
    
    # Create test suite
    loader = unittest.TestLoader()
    suite = unittest.TestSuite()
    
    # Add test classes in order
    for test_class in test_classes:
        suite.addTests(loader.loadTestsFromTestCase(test_class))
    
    # Run the tests
    return runner.run(suite)
